### ISSUE TITLE
Variables don't work in nuxt.js

### ISSUE THREAD

**Issue by flexscss** [egoist/styled-vue#11]
I try
```css
style: scss`
    .index {
      width: 100vh;
      height: 100vh;
      background: ${vm => vm.$store.state.theme.colors.primary};
      color: ${vm => vm.color};
    }
  `
```
but variables don't work
<img width="1439" alt="screen shot 2019-02-08 at 12 48 22" src="https://user-images.githubusercontent.com/6884695/52470659-df708b00-2b9f-11e9-96ad-9fc0770633ba.png">
